# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  schedule:
    - cron: '0 0 */2 * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: "3.7"
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run main.py
      env:
        BJYOUTH_USERNAME: ${{ secrets.BJYOUTH_USERNAME }}
        BJYOUTH_PASSWORD: ${{ secrets.BJYOUTH_PASSWORD }}
        SERVERCHAN_KEY: ${{ secrets.SERVERCHAN_KEY }}
      run: |
        python main.py
